----------------------------------------------------
-- Purpose: CRC Fall Data Student Usage Analysis  --
-- Requestor: Michael Edwards                     --
-- Programmer: Felicia R. Williams                --
-- Date: 1/14/2020                                --
----------------------------------------------------

SELECT* FROM
(SELECT DISTINCT C.PERSONID, COUNT(DISTINCT DOORACCESSPOSTDATETIME)
 FROM EDWSTG.STG_CMP_CRC_TURNSTILEDATA_TBL C
 WHERE DOORACCESSPOSTDATETIME BETWEEN TO_Date('2019-08-01' ,'YYYY-MM-DD') AND TO_Date('2019-12-31' ,'YYYY-MM-DD')
 GROUP BY C.PERSONID) CRC

INNER JOIN 

 (SELECT 
    DISTINCT AGG.GTID AS "GTID" , 
    AGG.GPA AS "GPA", 
    AGG.GENDER_NAME AS "Sex", 
    AGG.RACE_ETHN_COMB_NAME AS "Race/Ethnicity", 
    AGG.LVL_CODE AS "Student Level", 
    AGG.FRSHMN_CHRT_TRM_CODE AS "FRSHMN_CHRT_TRM", 
    AGG.MATRICULATION_TRM_CODE AS "MATRICULATION_TRM", 
    AGG.RESIDENCY_NAME AS "Residency",
    MAX(AGG1.GRADUATION_TERM_CODE) AS "GRADUATION_TERM", 
    AGG2.PRI_COLLEGE_NAME AS "College"
    
FROM EDW.AGG_STU_GPA_TERM_MVW AGG 
LEFT JOIN  EDW.AGG_STU_OUTCOME_MVW AGG1 ON AGG1.PIDM = AGG.PIDM 
LEFT JOIN  EDW.AGG_STU_ENRL_MVW AGG2 ON AGG2.PIDM = AGG.PIDM AND AGG2.TERM_CODE = AGG.TRM_CODE
WHERE 
AGG.TRM_CODE = '201908' 


GROUP BY 
    AGG.GTID, 
    AGG.GPA, 
    AGG.GENDER_NAME, 
    AGG.RACE_ETHN_COMB_NAME, 
    AGG.LVL_CODE, 
    AGG.FRSHMN_CHRT_TRM_CODE, 
    AGG.MATRICULATION_TRM_CODE, 
    AGG.RESIDENCY_NAME,
    AGG2.PRI_COLLEGE_NAME) Student
ON CRC.PERSONID = Student.GTID
	